version: '3'

services:
  app:
    image: app
    restart: always
    build: ./
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - 8000:4000
    command: sh -c 'npm i && npm run dev'
    environment:
      - MONGO_URI=mongodb://mongo:27017
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ../tmp/mongo-db:/data/db
    ports:
      - 27017:27017
