name: Deploy to Heroku

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: 'nodejs-otus-apollo'
          heroku_email: 'shilovkos@gmail.com'
